import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {

  docsSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Getting started',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'getting-started',
        },
      ]
    },
    {
      type: 'category',
      label: 'Guides',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'guides',
        },
      ]

    }
  ],

  communitySidebar: [
    {
      type: 'autogenerated',
      dirName: 'community',
    },
    {
      type: 'link',
      label: 'Chat with us on Discord',
      href: 'https://discord.gg/sjrw8QXNks',
    }
  ],
  
  apiSidebar: [
        {
          type: 'doc',
          id: 'api/index',
          label: 'Index',
        },
        {
          type: 'category',
          label: 'Variables',
          collapsed: false,
          items: [
            {
              type: 'autogenerated',
              dirName: 'api/variables',
            },
          ],
        },
        {
          type: 'category',
          label: 'Classes',
          collapsed: false,
          items: [
            {
              type: 'autogenerated',
              dirName: 'api/classes',
            },
          ],
        },
        {
          type: 'category',
          label: 'Interfaces',
          collapsed: false,
          items: [
            {
              type: 'autogenerated',
              dirName: 'api/interfaces',
            },
          ],
        },
        {
          type: 'category',
          label: 'Namespaces',
          collapsed: false,
          items: [
            {
              type: 'autogenerated',
              dirName: 'api/p5.asciify/namespaces',
            },
          ],
        }
      ],

      legalSidebar: [
        { 
          type: 'autogenerated',
          dirName: 'legal',
        }
      ],
};

export default sidebars;
